// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxaCFsdRqAbAnUgCjm9nZJTsEXeEXfx9w',
    appId: '1:956331446509:web:4d074422f7827e7b18fce4',
    messagingSenderId: '956331446509',
    projectId: 'project-security-a7e33',
    authDomain: 'project-security-a7e33.firebaseapp.com',
    storageBucket: 'project-security-a7e33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3UTj8RN0ri9fKt_Moru8nZt2vkzmYKFw',
    appId: '1:956331446509:android:c523080fdedce8a718fce4',
    messagingSenderId: '956331446509',
    projectId: 'project-security-a7e33',
    storageBucket: 'project-security-a7e33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDznbWkzpP8pE_J-OBgPkrxpvjdgzvjzL4',
    appId: '1:956331446509:ios:9213a7a28683301018fce4',
    messagingSenderId: '956331446509',
    projectId: 'project-security-a7e33',
    storageBucket: 'project-security-a7e33.firebasestorage.app',
    iosBundleId: 'com.example.passwordProject',
  );
}
